# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Pay-As-You-Go(2daf202c-149e-49a5-b14d-6b4cf65f409f)'
    appType: 'functionAppLinux'
    appName: 'TESTAPP1991'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.10'
    deploymentMethod: 'auto'
